export const ALLVIDEO = 'ALLVIDEO';
export const TOGGLE_VIDEO_FETCHING_STATE = "TOGGLE_VIDEO_FETCHING_STATE";
export const CURRENT_VIDEO = 'CURRENT_VIDEO';
export const SET_COMMENTS = 'SET_COMMENTS';
export const TOGGLE_CURRENT_VIDEO = 'TOGGLE_CURRENT_VIDEO';
export const SEARCHVIDEO = 'SEARCHVIDEO'